version: "3.9"

services:
  node:
    container_name: api_node
    restart: always
    depends_on:
      - mongo_container
    build: ./
    env_file: ./.env
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/node/app
      - node_modules:/source/node_modules

volumes:
  node_modules: {}